import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeroSectionWithNavbar from "@/shared/HeroSectionWithNavbar/HeroSectionWithNavbar";
import Footer from "@/shared/Footer/Footer";
import AuthProvider from "./context/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ingre-Dish",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <AuthProvider>
         <HeroSectionWithNavbar></HeroSectionWithNavbar>
        {children}
        <Footer></Footer>
       </AuthProvider>
      </body>
    </html>
  );
}
